spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: gjf
    password: gjf613
    url: jdbc:mysql://192.168.1.66:3306/lt_trade?useUnicode=true&characterEncoding=utf-8
    druid:
      initial-size: 4 #初始化时建立的连接数
      max-active: 8 #最大活跃数
      max-wait: 60000 #等待超时时间
      filter: stat,wall #监控与SQL注入过滤器
      stat-view-servlet: #监控页面
        enabled: true
        login-username: gailt
        login-password: gailt
  redis:
    host: 192.168.1.68
    port: 6379
    password: gjf*#123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0
  thymeleaf:
      cache: false
      encoding: UTF-8
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
  executor:
    core-pool-size: 4
    max-pool-size: 8
    keep-alive-seconds: 300
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/

finanace:
  system:
    python:
      profile: C:/python37/python
      day-line: D:/workspace-python/day_line.py
      week-line: D:/workspace-python/week_line.py
      month-line: D:/workspace-python/month_line.py
  comsumer:
    daily-basic: DAILY-CONSUMER-GROUP-HOME
    day-line: DAYLINE-CONSUMER-GROUP-HOME
    week-line: WEEKLINE-CONSUMER-GROUP-HOME
    plate-line: PLATELINE-CONSUMER-GROUP-HOME